version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - '5173:5173'
    environment:
      - VITE_APP_API=http://backend:3000
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - '3001:3000'
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: example
      DATABASE_NAME: candidates
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: candidates
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - '5432:5432'